// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Match struct {
	ID     int64
	Round  int64
	Winner string
	Loser  string
}

type Playlist struct {
	ID   string
	Name sql.NullString
	Url  sql.NullString
}

type PlaylistItem struct {
	ID       string
	Title    sql.NullString
	Artists  sql.NullString
	Image    sql.NullString
	Playlist string
}

type Round struct {
	ID      int64
	Session int64
	Number  int64
}

type Session struct {
	ID       int64
	Playlist string
}

type User struct {
	ID             string
	CurrentSession sql.NullInt64
}
