// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: session.sql

package db

import (
	"context"
	"database/sql"
)

const addMatch = `-- name: AddMatch :exec
INSERT INTO match
(id, session, round_number, winner, loser) VALUES (NULL, ?, ?, ?, ?)
`

type AddMatchParams struct {
	Session     int64
	RoundNumber int64
	Winner      string
	Loser       string
}

func (q *Queries) AddMatch(ctx context.Context, arg AddMatchParams) error {
	_, err := q.exec(ctx, q.addMatchStmt, addMatch,
		arg.Session,
		arg.RoundNumber,
		arg.Winner,
		arg.Loser,
	)
	return err
}

const addSession = `-- name: AddSession :one
INSERT INTO session
(id, playlist, current_round, user, winner) VALUES (NULL, ?, 0, ?, NULL)
RETURNING session.id
`

type AddSessionParams struct {
	Playlist string
	User     string
}

func (q *Queries) AddSession(ctx context.Context, arg AddSessionParams) (int64, error) {
	row := q.queryRow(ctx, q.addSessionStmt, addSession, arg.Playlist, arg.User)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getCurrentRound = `-- name: GetCurrentRound :one
SELECT current_round FROM session
WHERE id = ?
`

func (q *Queries) GetCurrentRound(ctx context.Context, id int64) (int64, error) {
	row := q.queryRow(ctx, q.getCurrentRoundStmt, getCurrentRound, id)
	var current_round int64
	err := row.Scan(&current_round)
	return current_round, err
}

const getWinner = `-- name: GetWinner :one
SELECT winner FROM session
WHERE id = ?
`

func (q *Queries) GetWinner(ctx context.Context, id int64) (sql.NullString, error) {
	row := q.queryRow(ctx, q.getWinnerStmt, getWinner, id)
	var winner sql.NullString
	err := row.Scan(&winner)
	return winner, err
}

const setCurrentRound = `-- name: SetCurrentRound :exec
UPDATE session
SET current_round = ?
WHERE id = ?
`

type SetCurrentRoundParams struct {
	CurrentRound int64
	ID           int64
}

func (q *Queries) SetCurrentRound(ctx context.Context, arg SetCurrentRoundParams) error {
	_, err := q.exec(ctx, q.setCurrentRoundStmt, setCurrentRound, arg.CurrentRound, arg.ID)
	return err
}

const setWinner = `-- name: SetWinner :exec
UPDATE session
SET winner = ?
WHERE id = ?
`

type SetWinnerParams struct {
	Winner sql.NullString
	ID     int64
}

func (q *Queries) SetWinner(ctx context.Context, arg SetWinnerParams) error {
	_, err := q.exec(ctx, q.setWinnerStmt, setWinner, arg.Winner, arg.ID)
	return err
}
